# Generated by Django 5.0.6 on 2024-07-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoring',
            options={'ordering': ('-score', '-longevity'), 'verbose_name': 'Scoring', 'verbose_name_plural': 'Scoring'},
        ),
    ]
